function dispshares(n)
global global_struct;

if n==3
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    figure
    imshow(s1);title('Share 1');
    pause(3);
    imshow(s1);title('Share 2');
    pause(3);
    imshow(s1);title('Share 3');
    pause(3);

elseif n==4
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s2);title('Share 2');
    pause(2);
    imshow(s3);title('Share 3');
    pause(2);
    imshow(s4);title('Share 4');
    pause(2);
    
elseif n==5
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
     imshow(s1);title('Share 5');
    pause(2);

elseif n==6
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    figure
  imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
    
elseif n==7
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);

elseif n==8
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    figure
   imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
  
elseif n==9
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);

elseif n==10
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    figure
  imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
    
elseif n==11
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    
elseif n==12
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
   
elseif n==13
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
   
elseif n==14
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    
elseif n==15
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
    imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
   imshow(s1);title('Share 15');
    pause(2);
    
elseif n==16
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
     s16=global_struct.s16;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
    imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
   imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
    
elseif n==17
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
     imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
    
elseif n==18
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    figure
    imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
    imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
   imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    
elseif n==19
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    
elseif n==20
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    
elseif n==21
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
    s21=global_struct.s21;
    figure
      imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    
elseif n==22
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
    s21=global_struct.s21;
    s22=global_struct.s22;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2); 
    
elseif n==23
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
    s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
    s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
   
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    
elseif n==24
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
    
    elseif n==25
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
    
   elseif n==26
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
    
    elseif n==27
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
    
    elseif n==28
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
s28=global_struct.s28;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
imshow(s1);title('Share 28');
    pause(2);
    
    elseif n==29
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
s28=global_struct.s28;
s29=global_struct.s29;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
imshow(s1);title('Share 28');
    pause(2);
imshow(s1);title('Share 29');
    pause(2);
    
    elseif n==30
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
s28=global_struct.s28;
s29=global_struct.s29;
s30=global_struct.s30;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
imshow(s1);title('Share 28');
    pause(2);
imshow(s1);title('Share 29');
    pause(2);
imshow(s1);title('Share 30');
    pause(2);
    
    elseif n==31
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
s28=global_struct.s28;
s29=global_struct.s29;
s30=global_struct.s30;
s31=global_struct.s31;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
imshow(s1);title('Share 28');
    pause(2);
imshow(s1);title('Share 29');
    pause(2);
imshow(s1);title('Share 30');
    pause(2);
imshow(s1);title('Share 31');
    pause(2);
    
    elseif n==32
    s1=global_struct.s1;
    s2=global_struct.s2;
    s3=global_struct.s3;
    s4=global_struct.s4;
s5=global_struct.s5;
    s6=global_struct.s6;
    s7=global_struct.s7;
    s8=global_struct.s8;
    s9=global_struct.s9;
    s10=global_struct.s10;
    s11=global_struct.s11;
    s12=global_struct.s12;
    s13=global_struct.s13;
    s14=global_struct.s14;
    s15=global_struct.s15;
    s16=global_struct.s16;
    s17=global_struct.s17;
    s18=global_struct.s18;
    s19=global_struct.s19;
    s20=global_struct.s20;
     s21=global_struct.s21;
    s22=global_struct.s22;
    s23=global_struct.s23;
    s24=global_struct.s24;
s25=global_struct.s25;
s26=global_struct.s26;
s27=global_struct.s27;
s28=global_struct.s28;
s29=global_struct.s29;
s30=global_struct.s30;
s31=global_struct.s31;
s32=global_struct.s32;
    figure
     imshow(s1);title('Share 1');
    pause(2);
    imshow(s1);title('Share 2');
    pause(2);
    imshow(s1);title('Share 3');
    pause(2);
    imshow(s1);title('Share 4');
    pause(2);
       imshow(s1);title('Share 5');
    pause(2);
     imshow(s1);title('Share 6');
    pause(2);
     imshow(s1);title('Share 7');
    pause(2);
     imshow(s1);title('Share 8');
    pause(2);
    imshow(s1);title('Share 9');
    pause(2);
    imshow(s1);title('Share 10');
    pause(2);
     imshow(s1);title('Share 11');
    pause(2);
    imshow(s1);title('Share 12');
    pause(2);
    imshow(s1);title('Share 13');
    pause(2);
    imshow(s1);title('Share 14');
    pause(2);
    imshow(s1);title('Share 15');
    pause(2);
     imshow(s1);title('Share 16');
    pause(2);
     imshow(s1);title('Share 17');
    pause(2);
     imshow(s1);title('Share 18');
    pause(2);
    imshow(s1);title('Share 19');
    pause(2);
    imshow(s1);title('Share 20');
    pause(2);
    imshow(s1);title('Share 21');
    pause(2);
    imshow(s1);title('Share 22');
    pause(2);
    imshow(s1);title('Share 23');
    pause(2);
    imshow(s1);title('Share 24');
    pause(2);
imshow(s1);title('Share 25');
    pause(2);
imshow(s1);title('Share 26');
    pause(2);
imshow(s1);title('Share 27');
    pause(2);
imshow(s1);title('Share 28');
    pause(2);
imshow(s1);title('Share 29');
    pause(2);
imshow(s1);title('Share 30');
    pause(2);
imshow(s1);title('Share 31');
    pause(2);
imshow(s1);title('Share 32');
    pause(2);
end


end